# diccionairio para unir clases repetidas
category_mapping = {
    'ESTATUS DE DESEMBOLSO 2014-2017': 'Estatus de desembolso',
    'Finanza y Firma de Convenio / ESTATUS DE DESEMBOLSO': 'Estatus de desembolso',
    'BLOQUEO DEL DESEMBOLSO POR PARTE DEL FCI': 'Estatus de desembolso',
    'ESTATUS DE DESEMBOLSO OTROS FINANCIAMIENTOS': 'Estatus de desembolso',
    'Denuncias, Reclamos y Sugerencias / Agradecimientos': 'Reclamos, sugerencias y agradecimientos',
    'Agradecimientos y Sugerencias': 'Reclamos, sugerencias y agradecimientos',
    'AGRADECIMIENTO': 'Reclamos, sugerencias y agradecimientos',
    'Otros / AGRADECIMIENTO': 'Reclamos, sugerencias y agradecimientos',
    'Carga y estatus de proyectos / DIFICULTAD EN CARGA DE ARCHIVO EN EL MODULO DE REGISTRAR': 'Dificultad en el modulo de registrar',
    'Carga y estatus de proyectos / DIFICULTAD PARA EDITAR UN CAMPO EN EL MODULO DE REGISTRAR': 'Dificultad en el modulo de registrar',
    'DIFICULTAD PARA EDITAR UN CAMPO EN EL MODULO DE  REGISTRAR': 'Dificultad en el modulo de registrar',
    'DESCONOCIMIENTO DEL PROCESO DE LA RENDICIÓN DE CUENTAS-VOCERIA': 'Rendición de cuentas',
    'DIFICULTAD PARA EDITAR UN CAMPO EN EL MODULO DE RENDICION DE CUENTAS': 'Rendición de cuentas',
    'DIFICULTAD PARA IMPRIMIR EL INFORME DE RENDICION DE CUENTAS': 'Rendición de cuentas',
    'DESCONOCIMIENTO DEL MOMENTO DE LA RENDICIÓN DE CUENTAS-VOCERÍA': 'Rendición de cuentas',
    'RENDICIÓN DE CUENTAS DEL PROYECTO': 'Rendición de cuentas',
    'PROBLEMAS EN LA RENDICION POR CAMBIO DE PROYECTO SIN AUTORIZACION DEL FCI': 'Rendición de cuentas',
    'Rendición de Cuenta y Controlaría Social / DIFICULTAD PARA EDITAR UN CAMPO EN EL MODULO DE RENDICIÓN DE CUENTAS': 'Rendición de cuentas',
    'Rendición de Cuenta y Controlaría Social / DIFICULTAD PARA IMPRIMIR EL INFORME DE RENDICIÓN DE CUENTAS': 'Rendición de cuentas',
    'Rendición de Cuenta y Controlaría Social / DESCONOCIMIENTO DEL MOMENTO DE LA RENDICIÓN DE CUENTAS-VOCERÍA': 'Rendición de cuentas',
    'Rendición de Cuenta y Controlaría Social / DESCONOCIMIENTO DEL PROCESO DE LA RENDICIÓN DE CUENTAS-VOCERÍA': 'Rendición de cuentas',
    'Rendición de Cuenta y Controlaría Social / DESCONOCIMIENTO DEL PROCESO DE INFORME DE AVANCE-VOCERÍA': 'Rendición de cuentas',
    'Rendición de Cuenta y Controlaría Social / DIFICULTAD PARA EDITAR UN CAMPO EN EL MODULO DE INFORMES DE AVANCES': 'Rendición de cuentas',
    'Rendición de Cuenta y Controlaría Social / DENUNCIAS EN LA EJECUCIÓN DEL PROYECTO': 'Rendición de cuentas',
    'Servicio Publico / Agua': 'Agua',
    'Servicio Publico / Electricidad': 'Electricidad',
    'Servicio Publico / Vialidad': 'Vialidad',
    'Servicio Publico / Vivienda': 'Vivienda',
    'Servicio Publico / Salud': 'Salud',
    'Servicio Publico / Educación': 'Educación',
    'Servicio Publico / Deporte': 'Deporte',
    'CAMBIO DE VOCERIAS DEL CONSEJO COMUNAL': 'Cambio de vocería',
    'CAMBIO DE VOCERIA RESPONSABLE DEL PROYECTO': 'Cambio de vocería',
    'Voceros y usuarios / CAMBIO DE VOCERÍAS DE LA ORGANIZACIÓN (PROMOTORES)': 'Cambio de vocería',
    'Carga y estatus de proyectos / CAMBIO DE VOCERO(A) RESPONSABLE': 'Cambio de vocería',
    'Ejecución de Proyecto / CAMBIO DE META': 'Cambio de meta',
    'CAMBIO DE META ': 'Cambio de meta',
    'Ejecución de Proyecto / ACOMPAÑAMIENTO TÉCNICO': 'Acompañamiento técnico',
    'ACOMPAÑAMIENTO TÉCNICO': 'Acompañamiento técnico',
    'SOLICITUD DE ACTIVACION USUARIO SINCO': 'Solicitud de activación usuario sinco',
    'Voceros y usuarios / SOLICITUD DE ACTIVACIÓN USUARIO': 'Solicitud de activación usuario sinco',
    'PASOS PARA REGISTRAR UN PROYECTO': 'Pasos para registrar un proyecto',
    'Carga y estatus de proyectos / PASOS PARA REGISTRAR UN PROYECTO': 'Pasos para registrar un proyecto',
    'PROCESO DE VALORACION DEL PROYECTO': 'Proceso de valoración del proyecto',
    'Carga y estatus de proyectos / PROCESO DE VALORACIÓN DEL PROYECTO': 'Proceso de valoración del proyecto',
    'Carga y estatus de proyectos / CAUSAS DE LA CANCELACIÓN DEL PROYECTO POR EL FCI': 'Cancelación de proyecto',
    'CAUSAS DE LA CANCELACION  DEL PROYECTO POR EL FCI': 'Cancelación de proyecto',
    'Carga y estatus de proyectos / CANCELAR PROYECTO REGISTRADO NO APROBADO': 'Cancelación de proyecto',
    'COMO CANCELAR UN PROYECTO REGISTRADO (EN EVALUACION)(ANTERIOR 06-03)': 'Cancelación de proyecto',
    'PROCEDIMIENTO PARA EL CAMBIO DE CORREO ELECTRÓNICO': 'Cambio de correo electrónico',
    'Voceros y usuarios / CAMBIO DE CORREO ELECTRÓNICO': 'Cambio de correo electrónico',
    'PROBLEMAS POR CUENTAS BANCARIAS DE OBPP BLOQUEADAS Y CAMBIO DE CUENTA': 'Problemas con cuentas bancarias',
    'Finanza y Firma de Convenio / PROBLEMAS POR CUENTAS BANCARIAS': 'Problemas con cuentas bancarias',
    'Comunicaciones / RESPUESTA A COMUNICACIÓN INFORMATIVA': 'Respuesta a comunicación emitida',
    'RESPUESTA A COMUNICACIÓN EMITIDA POR EL FCI': 'Respuesta a comunicación emitida',
    'OTROS': 'Otros',
    'Servicio Publico / Otros': 'Otros',
    'Organizaciones / PROBLEMAS CON EL RIF O CÓDIGO SITUR': 'Problemas con el RIF o código Situr',
    'PROBLEMAS CON EL RIF O CÓDIGO SITUR ': 'Problemas con el RIF o código Situr',
    'Otros / AYUDAS SOCIALES VARIAS': 'Ayudas sociales varias',
    'AYUDAS SOCIALES VARIAS': 'Ayudas sociales varias',
    'Otros / SEGUIMIENTO AL TRAMITE': 'Seguimiento al tramite',
    'SEGUIMIENTO AL TRAMITE ': 'Seguimiento al tramite',
    'Finanza y Firma de Convenio / CANCELACIÓN DE PROYECTO APROBADO Y REINTEGRO DE LOS RECURSOS': 'Cancelación de proyecto aprobado y reintegro de insumos',
    'REINTEGRO DE LOS RECURSOS': 'Cancelación de proyecto aprobado y reintegro de insumos'
}