# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFZs74L6LGJXfZB2Un7ICMhB9ndOgNTk
"""

import re
def strip_tags_and_emails(value):
    """
    Removes HTML tags and email addresses from a string.
    Args:
        value (str): A string containing text with HTML tags and/or
        email addresses.
    Returns:
        str: The string with HTML tags and email addresses removed.
    """
    value = re.sub(r'<[^>]*?>', '', value)
    value = re.sub(r"[\w._%+-]+@[\w.-]+\.[a-zA-Z]{2,64}", "", value)
    return value